### ISSUE TITLE
关于VOC2007数据集的制作

### ISSUE THREAD

**Issue by Polaris-SDU** [murphypei/create-pascal-voc-dataset#1]
同学你好：请问这个程序可以把 ICDAR2017 数据集转换成 VOC2007 数据集吗？谢谢。

**Comment by murphypei** [comment]
@Polaris-SDU 这个是利用图片和标注直接做VOC2007数据集，和你原始数据集无关，但是你可能需要从原始数据集中提取数据，然后准备成程序需要的输入就行了

**Comment by Polaris-SDU** [comment]
谢谢你啦～
