### ISSUE TITLE
关于用法的不解

### ISSUE THREAD

**Issue by qiangruoyu** [murphypei/create-pascal-voc-dataset#3]
第三部不是很懂，不知道都是需要配置哪个文件，和文件里面的哪个变量。
另外 box的坐标是按照左上角和右下角两个点确定的吧

**Comment by murphypei** [comment]
> 第三部不是很懂，不知道都是需要配置哪个文件，和文件里面的哪个变量。 另外 box的坐标是按照左上角和右下角两个点确定的吧

第三部分是配置数据集的信息，你需要编写类似 inria_example 文件。box坐标是左上角和右下角。
