### ISSUE TITLE
utils.fileutils 拷贝问题

### ISSUE THREAD

**Issue by berniel** [murphypei/create-pascal-voc-dataset#6]
拷贝文件的时候先把源文件复制到目标文件夹，再给源文件改名，会遇到源文件名覆盖掉目标文件夹里面改好名的文件吧？为什么不直接复制到目标文件夹下的文件呢？
现在：src/000001.jpg -> (copy to) dst/000001.jpg ->(rename)dst/000100.jpg
建议：src/000001.jpg -> (copy to) dst/000100.jpg

**Comment by murphypei** [comment]
> 拷贝文件的时候先把源文件复制到目标文件夹，再给源文件改名，会遇到源文件名覆盖掉目标文件夹里面改好名的文件吧？为什么不直接复制到目标文件夹下的文件呢？ 现在：src/000001.jpg -> (copy to) dst/000001.jpg ->(rename)dst/000100.jpg 建议：src/000001.jpg -> (copy to) dst/000100.jpg

谢谢，已经修改了。
